name: 'telegram_dw'
version: '1.0'

profile: 'profiles.yml'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

models:
  telegram_warehouse:
    +materialized: table