name: 'telegram_dw'
version: '1.0'

profile: 'profiles.yml'
profile: 'telegram_dw'

analysis-paths: ["analyses"]
model-paths: ["models"]
seed-paths: ["data"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  telegram_warehouse:
    +materialized: table